logger_level: 0
server:
  port: 8080
  lb_method: LC  # RR (RoundRobin) || LC (LeastConnections)
rate_limiter:
  enabled: true
  db: 
    host: cache
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cleanup_interval: 5m
  refill_interval: 1s
  bucket_expiration : 1h
  default:
    refill_rate: 5
    max_tokens: 10 
pool: 
  urls:
  - http://127.0.0.1:8081
  - http://127.0.0.1:8082
  - http://127.0.0.1:8083
  healthcheck: 
    timeout: 2s
    endpoint: /healthcheck

