version: '3.9'
services:
  loadbalancer:
    build: ./
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - cache
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "curl", "-f", "http://127.0.0.1:8080/healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - net      

networks:
  net:
    driver: bridge